CREATE DATABASE Shynkar_Task8_Foxminded;
GO

USE Shynkar_Task8_Foxminded;
GO

CREATE TABLE COURSES (
    ID int UNIQUE IDENTITY(1,1),
    NAME varchar(255) NOT NULL,
    DESCRIPTION varchar(1000),
    PRIMARY KEY (ID),
    CONSTRAINT UQ_Courses_Name UNIQUE (NAME)
);

CREATE INDEX idx_courses_name
ON COURSES (NAME);

CREATE TABLE TEACHERS(
    ID int IDENTITY(1,1),
    FIRST_NAME varchar(255) NOT NULL,
    LAST_NAME varchar(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT UQ_Teachers_Name UNIQUE (FIRST_NAME, LAST_NAME)
);

CREATE INDEX idx_teachers_name
ON TEACHERS (LAST_NAME, FIRST_NAME);

CREATE TABLE GROUPS(
    ID int IDENTITY(1,1),
    COURSE_ID int NOT NULL,
	TEACHER_ID int NOT NULL,
    NAME varchar(255) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(ID),
	FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS(ID),
    CONSTRAINT UQ_Groups_Name UNIQUE (COURSE_ID, TEACHER_ID, NAME)
);

CREATE INDEX idx_groups_name
ON GROUPS (NAME);

CREATE TABLE STUDENTS(
    ID int IDENTITY(1,1),
    GROUP_ID int NOT NULL,
    FIRST_NAME varchar(255) NOT NULL,
    LAST_NAME varchar(255) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(ID),
    CONSTRAINT UQ_Students_Name UNIQUE (GROUP_ID, FIRST_NAME, LAST_NAME)
);

CREATE INDEX idx_students_name
ON STUDENTS (LAST_NAME, FIRST_NAME);
