//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foxminded.Curriculum.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProgramInterface {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProgramInterface() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foxminded.Curriculum.App.Resources.ProgramInterface", typeof(ProgramInterface).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Student.
        /// </summary>
        public static string AddStudentButtonText {
            get {
                return ResourceManager.GetString("AddStudentButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Teacher.
        /// </summary>
        public static string AddTeacherButtonText {
            get {
                return ResourceManager.GetString("AddTeacherButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a teacher.
        /// </summary>
        public static string ChoiceTeacherForGroup {
            get {
                return ResourceManager.GetString("ChoiceTeacherForGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter first name.
        /// </summary>
        public static string ColumnForInputFirstName {
            get {
                return ResourceManager.GetString("ColumnForInputFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Group name.
        /// </summary>
        public static string ColumnForInputGroupNameText {
            get {
                return ResourceManager.GetString("ColumnForInputGroupNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter last name.
        /// </summary>
        public static string ColumnForInputLastName {
            get {
                return ResourceManager.GetString("ColumnForInputLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string CoursesText {
            get {
                return ResourceManager.GetString("CoursesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Group.
        /// </summary>
        public static string CreateGroupText {
            get {
                return ResourceManager.GetString("CreateGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Group.
        /// </summary>
        public static string DeleteGroupText {
            get {
                return ResourceManager.GetString("DeleteGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Student.
        /// </summary>
        public static string DeleteStudentButtonText {
            get {
                return ResourceManager.GetString("DeleteStudentButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Teacher.
        /// </summary>
        public static string DeleteTeacherButtonText {
            get {
                return ResourceManager.GetString("DeleteTeacherButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Group.
        /// </summary>
        public static string EditGroupText {
            get {
                return ResourceManager.GetString("EditGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit student`s data.
        /// </summary>
        public static string EditStudentButtonText {
            get {
                return ResourceManager.GetString("EditStudentButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit teacher`s data.
        /// </summary>
        public static string EditTeacherButtonText {
            get {
                return ResourceManager.GetString("EditTeacherButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Students to CSV.
        /// </summary>
        public static string ExportToCSVText {
            get {
                return ResourceManager.GetString("ExportToCSVText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstNameText {
            get {
                return ResourceManager.GetString("FirstNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program was created by Foxminded student Nikita Shynkar.
        /// </summary>
        public static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate DOCX/PDF.
        /// </summary>
        public static string GenerateDocumentText {
            get {
                return ResourceManager.GetString("GenerateDocumentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group settings.
        /// </summary>
        public static string GroupSettingsHeaderText {
            get {
                return ResourceManager.GetString("GroupSettingsHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string GroupsText {
            get {
                return ResourceManager.GetString("GroupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Students from CSV.
        /// </summary>
        public static string ImportFromCSVText {
            get {
                return ResourceManager.GetString("ImportFromCSVText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a CSV file to import students.
        /// </summary>
        public static string ImportStudentsHeaderFolderText {
            get {
                return ResourceManager.GetString("ImportStudentsHeaderFolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastNameText {
            get {
                return ResourceManager.GetString("LastNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person`s data settings.
        /// </summary>
        public static string PersonSettingsHeaderText {
            get {
                return ResourceManager.GetString("PersonSettingsHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string ReturnText {
            get {
                return ResourceManager.GetString("ReturnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButtonText {
            get {
                return ResourceManager.GetString("SaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string StudentsText {
            get {
                return ResourceManager.GetString("StudentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string TeacherText {
            get {
                return ResourceManager.GetString("TeacherText", resourceCulture);
            }
        }
    }
}
