//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foxminded.Curriculum.App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TechnicalMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TechnicalMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foxminded.Curriculum.App.Resources.TechnicalMessage", typeof(TechnicalMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can`t get access to directory!.
        /// </summary>
        public static string AccessToDirectoryExceptionText {
            get {
                return ResourceManager.GetString("AccessToDirectoryExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can`t find path!.
        /// </summary>
        public static string CantFoundPathExceptionText {
            get {
                return ResourceManager.GetString("CantFoundPathExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete students from group first!.
        /// </summary>
        public static string DeleteGroupWithStudentsInExceptionText {
            get {
                return ResourceManager.GetString("DeleteGroupWithStudentsInExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete teacher from group first!.
        /// </summary>
        public static string DeleteGroupWithTeacherInExceptionText {
            get {
                return ResourceManager.GetString("DeleteGroupWithTeacherInExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same group is already in database!.
        /// </summary>
        public static string DuplicateExceptionGroupText {
            get {
                return ResourceManager.GetString("DuplicateExceptionGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same student is already in database!.
        /// </summary>
        public static string DuplicateExceptionStudentText {
            get {
                return ResourceManager.GetString("DuplicateExceptionStudentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same teacher is already in database!.
        /// </summary>
        public static string DuplicateExceptionTeacherText {
            get {
                return ResourceManager.GetString("DuplicateExceptionTeacherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please, contact the support..
        /// </summary>
        public static string ExceptionText {
            get {
                return ResourceManager.GetString("ExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is filled in incorrectly!.
        /// </summary>
        public static string FormatExceptionText {
            get {
                return ResourceManager.GetString("FormatExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is wrong data!.
        /// </summary>
        public static string NullExceptionText {
            get {
                return ResourceManager.GetString("NullExceptionText", resourceCulture);
            }
        }
    }
}
